# Generated by Django 3.2.7 on 2021-09-03 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homes',
            new_name='home',
        ),
    ]
